export const GET_REVENUE_DATA_REQUEST = "GET_REVENUE_DATA_REQUEST";
export const GET_REVENUE_DATA_SUCCESS = "GET_REVENUE_DATA_SUCCESS";
export const GET_REVENUE_DATA_ERROR = "GET_REVENUE_DATA_ERROR";

export const GET_MEMBER_DATA_REQUEST = "GET_MEMBER_DATA_REQUEST";
export const GET_MEMBER_DATA_SUCCESS = "GET_MEMBER_DATA_SUCCESS";
export const GET_MEMBER_DATA_ERROR = "GET_MEMBER_DATA_ERROR";

export const GET_CATEGORY_SALES_DATA_REQUEST = "GET_CATEGORY_SALES_DATA_REQUEST";
export const GET_CATEGORY_SALES_DATA_SUCCESS = "GET_CATEGORY_SALES_DATA_SUCCESS";
export const GET_CATEGORY_SALES_DATA_ERROR = "GET_CATEGORY_SALES_DATA_ERROR";
