export const GET_GIFT_CARDS_REQUEST = 'GET_GIFT_CARDS_REQUEST';
export const GET_GIFT_CARDS_SUCCESS = 'GET_GIFT_CARDS_SUCCESS';
export const GET_GIFT_CARDS_ERROR = 'GET_GIFT_CARDS_ERROR';

export const SAVE_GIFT_CARDS_REQUEST = 'SAVE_GIFT_CARDS_REQUEST';
export const SAVE_GIFT_CARDS_SUCCESS = 'SAVE_GIFT_CARDS_SUCCESS';
export const SAVE_GIFT_CARDS_ERROR = 'SAVE_GIFT_CARDS_ERROR';

export const EDIT_GIFT_CARDS_REQUEST = 'EDIT_GIFT_CARDS_REQUEST';
export const EDIT_GIFT_CARDS_SUCCESS = 'EDIT_GIFT_CARDS_SUCCESS';
export const EDIT_GIFT_CARDS_ERROR = 'EDIT_GIFT_CARDS_ERROR';
