export const GET_SETTING_INFO_REQUEST = 'GET_SETTING_INFO_REQUEST';
export const GET_SETTING_INFO_SUCCESS = 'GET_SETTING_INFO_SUCCESS';
export const GET_SETTING_INFO_ERROR = 'GET_SETTING_INFO_ERROR';

export const UPDATE_SETTING_INFO_REQUEST = 'UPDATE_SETTING_INFO_REQUEST';
export const UPDATE_SETTING_INFO_SUCCESS = 'UPDATE_SETTING_INFO_SUCCESS';
export const UPDATE_SETTING_INFO_ERROR = 'UPDATE_SETTING_INFO_ERROR';
