export const GET_NOTIFICATION_REQUESTS = 'GET_NOTIFICATION_REQUESTS';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR';

export const READ_NOTIFICATION_REQUESTS = 'READ_NOTIFICATION_REQUESTS';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_ERROR = 'READ_NOTIFICATION_ERROR';
