export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const FILTER_VISIBLE_PRODUCTS = 'FILTER_VISIBLE_PRODUCTS';
export const FILTER_HIDDEN_PRODUCTS = 'FILTER_HIDDEN_PRODUCTS';
export const FILTER_OUT_OF_STOCK_PRODUCTS = 'FILTER_OUT_OF_STOCK_PRODUCTS';

export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_RESULT_MESSEGE = 'UPDATE_PRODUCT_RESULT_MESSEGE';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const SAVE_WEBINAR_REQUEST = 'SAVE_WEBINAR_REQUEST';
export const SAVE_WEBINAR_SUCCESS = 'SAVE_WEBINAR_SUCCESS';
export const SAVE_WEBINAR_ERROR = 'SAVE_WEBINAR_ERROR';

export const UPDATE_WEBINAR_REQUEST = 'UPDATE_WEBINAR_REQUEST';
export const UPDATE_WEBINAR_SUCCESS = 'UPDATE_WEBINAR_SUCCESS';
export const UPDATE_WEBINAR_ERROR = 'UPDATE_WEBINAR_ERROR';

export const DELETE_PRODUCT_IMAGES_REQUEST = 'DELETE_PRODUCT_IMAGES_REQUEST';
export const DELETE_PRODUCT_IMAGES_SUCCESS = 'DELETE_PRODUCT_IMAGES_SUCCESS';
export const DELETE_PRODUCT_IMAGES_ERROR = 'DELETE_PRODUCT_IMAGES_ERROR';

export const ADD_PRODUCT_IMAGES_REQUEST = 'ADD_PRODUCT_IMAGES_REQUEST';
export const ADD_PRODUCT_IMAGES_SUCCESS = 'ADD_PRODUCT_IMAGES_SUCCESS';
export const ADD_PRODUCT_IMAGES_ERROR = 'ADD_PRODUCT_IMAGES_ERROR';

export const GET_ALL_PRODUCT_IMAGES_REQUEST = 'GET_ALL_PRODUCT_IMAGES_REQUEST';
export const GET_ALL_PRODUCT_IMAGES_SUCCESS = 'GET_ALL_PRODUCT_IMAGES_SUCCESS';
export const GET_ALL_PRODUCT_IMAGES_ERROR = 'GET_ALL_PRODUCT_IMAGES_ERROR';


export const GET_SELECTED_PRODUCT_REQUEST = 'GET_SELECTED_PRODUCT_REQUEST';
export const GET_SELECTED_PRODUCT_SUCCESS = 'GET_SELECTED_PRODUCT_SUCCESS';
export const GET_SELECTED_PRODUCT_ERROR = 'GET_SELECTED_PRODUCT_ERROR';

export const GET_QUEUED_WEBINARS_REQUEST = 'GET_QUEUED_WEBINARS_REQUEST';
export const GET_QUEUED_WEBINARS_SUCCESS = 'GET_QUEUED_WEBINARS_SUCCESS';
export const GET_QUEUED_WEBINARS_ERROR = 'GET_QUEUED_WEBINARS_ERROR';

export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';

export const CLEAR_WEBINARS = 'CLEAR_WEBINARS';

export const CHANGE_PRODUCT_STATUS_REQUEST = 'CHANGE_PRODUCT_STATUS_REQUEST';

export const MOVE_WEBINAR_TO_QUEUE_REQUEST = 'MOVE_WEBINAR_TO_QUEUE_REQUEST';

export const CHANGE_PUBLISH_METHOD_FROM_QUEUE_REQUEST = 'CHANGE_PUBLISH_METHOD_FROM_QUEUE_REQUEST';

export const SAVE_WEBINAR_SEAT_WEBINAR_REQUEST = 'SAVE_WEBINAR_SEAT_WEBINAR_REQUEST';



