export const GET_LIST_COMPLETED_REQUEST = 'GET_LIST_COMPLETED_REQUEST';
export const GET_LIST_COMPLETED_SUCCESS = 'GET_LIST_COMPLETED_SUCCESS';
export const GET_LIST_COMPLETED_ERROR = 'GET_LIST_COMPLETED_ERROR';
export const SAVE_FFL_WINNERS_REQUEST = 'SAVE_FFL_WINNERS_REQUEST';
export const SAVE_FFL_WINNERS_SUCCESS = 'SAVE_FFL_WINNERS_SUCCESS';
export const SAVE_FFL_WINNERS_ERROR = 'SAVE_FFL_WINNERS_ERROR';
