export const GET_FAQ_REQUEST = "GET_FAQ_REQUEST";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_ERROR = "GET_FAQ_ERROR";

export const UPDATE_FAQ_REQUEST = "UPDATE_FAQ_REQUEST";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_ERROR = "UPDATE_FAQ_ERROR";

export const SAVE_FAQ_REQUEST = "SAVE_FAQ_REQUEST";
export const SAVE_FAQ_SUCCESS = "SAVE_FAQ_SUCCESS";
export const SAVE_FAQ_ERROR = "SAVE_FAQ_ERROR";

export const DELETE_FAQ_REQUEST = "DELETE_FAQ_REQUEST";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_ERROR = "DELETE_FAQ_ERROR";
export const SELECT_FAQ = "SELECT_FAQ";
