export const GET_PROMO_CODES_REQUEST = 'GET_PROMO_CODES_REQUEST';
export const GET_PROMO_CODES_SUCCESS = 'GET_PROMO_CODES_SUCCESS';
export const GET_PROMO_CODES_ERROR = 'GET_PROMO_CODES_ERROR';

export const SAVE_PROMO_CODES_REQUEST = 'SAVE_PROMO_CODES_REQUEST';
export const SAVE_PROMO_CODES_SUCCESS = 'SAVE_PROMO_CODES_SUCCESS';
export const SAVE_PROMO_CODES_ERROR = 'SAVE_PROMO_CODES_ERROR';
