export const GET_SOLD_OUT_WEBINARS_REQUEST = "GET_SOLD_OUT_WEBINARS_REQUEST";
export const GET_SOLD_OUT_WEBINARS_SUCCESS = "GET_SOLD_OUT_WEBINARS_SUCCESS";
export const GET_SOLD_OUT_WEBINARS_ERROR = "GET_SOLD_OUT_WEBINARS_ERROR";

export const SEND_LINK_WEBINAR_REQUEST = "SEND_LINK_WEBINAR_REQUEST";
export const SEND_LINK_WEBINAR_SUCCESS = "SEND_LINK_WEBINAR_SUCCESS";
export const SEND_LINK_WEBINAR_ERROR = "SEND_LINK_WEBINAR_ERROR";

export const LIST_USERS_WEBINAR_REQUEST = "LIST_WEBINARS_USERS_WEBINAR_REQUEST";
export const LIST_USERS_WEBINAR_SUCCESS = "LIST_WEBINARS_USERS_WEBINAR_SUCCESS";
export const LIST_USERS_WEBINAR_ERROR = "LIST_WEBINARS_USERS_WEBINAR_ERROR";
