export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const USERS_SEARCH_RESULT_REQUEST = 'USERS_SEARCH_RESULT_REQUEST';
export const USERS_SEARCH_RESULT_SUCCESS = 'USERS_SEARCH_RESULT_SUCCESS';
export const USERS_SEARCH_RESULT_ERROR = 'USERS_SEARCH_RESULT_ERROR';
