export const GET_SOLD_PHYSICAL_PRODUCTS_REQUEST = 'GET_SOLD_PHYSICAL_PRODUCTS_REQUEST';
export const GET_SOLD_PHYSICAL_PRODUCTS_SUCCESS = 'GET_SOLD_PHYSICAL_PRODUCTS_SUCCESS';
export const GET_SOLD_PHYSICAL_PRODUCTS_ERROR = 'GET_SOLD_PHYSICAL_PRODUCTS_ERROR';

export const UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_REQUEST = 'UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_REQUEST';
export const UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_SUCCESS = 'UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_SUCCESS';
export const UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_ERROR = 'UPDATE_SOLD_PHYSICAL_PRODUCT_FFL_ERROR';

