export const GET_SEATS_FOR_REFUND_REQUEST = 'GET_SEATS_FOR_REFUND_REQUEST';
export const GET_SEATS_FOR_REFUND_SUCCESS = 'GET_SEATS_FOR_REFUND_SUCCESS';
export const GET_SEATS_FOR_REFUND_ERROR = 'GET_SEATS_FOR_REFUND_ERROR';

export const SAVE_SEATS_FOR_REFUND_REQUEST = 'SAVE_SEATS_FOR_REFUND_REQUEST';
export const SAVE_SEATS_FOR_REFUND_SUCCESS = 'SAVE_SEATS_FOR_REFUND_SUCCESS';
export const SAVE_SEATS_FOR_REFUND_ERROR = 'SAVE_SEATS_FOR_REFUND_ERROR';


